Repository Monest-eco/monest-server, pull requests merged in 2021-12, with the labels that each got.

#7 Dockerize application
  .dockerignore
  .github/pull_request_template.md
  Dockerfile
  database.env
  docker-compose.yml
  sql/create_tables.sql
  src/app.service.ts
  src/main.ts
Labels: DevOps

#10 Generate fake data
  @types/fakeData.ts
  package.json
  src/app.controller.spec.ts
  src/app.module.ts
  src/app.service.ts
  src/data/data.controller.spec.ts
  src/data/data.controller.ts
  src/data/data.module.ts
  src/data/data.service.spec.ts
  src/data/data.service.ts
  src/fakeData.ts
  src/main.ts
  yarn.lock
Labels: enhancement, Server, Tests

#14 Generate fake data in time
  .gitignore
  @types/fakeData.ts
  data/.gitkeep
  src/fakeData.ts
  src/main.ts
Labels: enhancement, Server, v1.x.x

#19 MQTT server
  package.json
  src/main.ts
  src/mqtt/main.ts
  src/mqtt/mqttapp.controller.ts
  src/mqtt/mqttapp.module.ts
  tsconfig.json
  yarn.lock
Labels: documentation, Server, v1.x.x

#22 Save esp32 data in PG
  .gitignore
  database.env
  docker-compose.yml
  package.json
  sql/create_tables.sql
  sql/fill_tables.sql
  src/@types/esp32.ts
  src/app.module.ts
  src/data/data.controller.spec.ts
  src/data/data.controller.ts
  src/data/data.module.ts
  src/data/data.service.spec.ts
  src/data/data.service.ts
  src/esp32/esp32.service.ts
  src/esp32/esp32.ts
  src/main.ts
  src/mqtt/database/connect.ts
  src/mqtt/main.ts
  src/swagger/swagger.ts
  yarn.lock
Labels: enhancement, Server, v1.x.x

#16 Release v0.0.1
  .gitignore
  data/.gitkeep
  database.env
  docker-compose.yml
  package.json
  sql/create_tables.sql
  sql/fill_tables.sql
  src/@types/esp32.ts
  src/@types/fakeData.ts
  src/app.controller.spec.ts
  src/app.module.ts
  src/app.service.ts
  src/esp32/esp32.service.ts
  src/esp32/esp32.ts
  src/fakeData.ts
  src/main.ts
  src/mqtt/app.controller.ts
  src/mqtt/app.module.ts
  src/mqtt/database/connect.ts
  src/mqtt/main.ts
  src/mqtt/mqttapp.controller.ts
  src/mqtt/mqttapp.module.ts
  src/swagger/swagger.ts
  tsconfig.json
  yarn.lock
Labels: Server, v1.x.x, Release

#27 Default configuration monest-server
  Dockerfile
  docker-compose.yml
  src/@types/MonestConfig.ts
  src/configs/deafult.config.ts
  src/main.ts
  src/mqtt/database/connect.ts
  src/mqtt/main.ts
Labels: Server, v1.x.x

#28 Check .env value
  src/errors/monestError.ts
  src/main.ts
Labels: Server, v1.x.x

#30 Get all datas
  docker-compose.yml
  package.json
  src/app.module.ts
  src/esp32/esp32.service.ts
  src/hardware/hardware.controller.ts
  src/hardware/hardware.module.ts
  src/hardware/hardware.service.ts
  yarn.lock
Labels: enhancement, Server, v1.x.x

#29 Release v0.0.2
  Dockerfile
  docker-compose.yml
  package.json
  src/@types/MonestConfig.ts
  src/app.module.ts
  src/configs/deafult.config.ts
  src/errors/monestError.ts
  src/esp32/esp32.service.ts
  src/hardware/hardware.controller.ts
  src/hardware/hardware.module.ts
  src/hardware/hardware.service.ts
  src/main.ts
  src/mqtt/database/connect.ts
  src/mqtt/main.ts
  yarn.lock
Labels: Server, v1.x.x, Release

#41 Setup Websocket
  package.json
  src/@types/websockets.ts
  src/app.gateway.ts
  src/app.module.ts
  src/main.ts
  yarn.lock
Labels: enhancement, Server, v1.x.x

#40 Create actions for cash node-modules
  .github/workflows/main.yml
Labels: DevOps

#43 Create Websockets
  package.json
  src/@types/websockets.ts
  src/app.gateway.ts
  src/app.module.ts
  src/main.ts
  yarn.lock
Labels: enhancement, Server, v1.x.x

#45 Create MQTT class encaptulation
  src/mqtt/app.controller.ts
  src/mqtt/app.module.ts
  src/mqtt/main.ts
  src/mqtt/mqtt.ts
  src/mqtt/mqttapp.controller.ts
  src/mqtt/mqttapp.module.ts
Labels: enhancement, v1.x.x
